# References:
# https://github.com/mpeterv/hererocks
# https://github.com/kikito/middleclass/blob/master/.travis.yml
# http://luacheck.readthedocs.org/en/stable/cli.html#command-line-options

language: python
sudo: false

env:
  - LUA="lua=5.1"
  - LUA="lua=5.2"
  - LUA="lua=5.3"
  - LUA="luajit=2.0"
  - LUA="luajit=2.1"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin # Add directory with all installed binaries to PATH

install:
  - luarocks install luacheck
  - luarocks install busted
  - luarocks install luacov
  - luarocks install luacov-coveralls

script:
  - luacheck --no-unused-args --std max+busted *.lua src --ignore 512 --no-cache --globals display IMPORTATIONS application backgroundSound system Runtime native transition timer graphics audio
#  - busted --verbose --coverage

after_success:
  - luacov-coveralls --exclude $TRAVIS_BUILD_DIR/lua_install

branches:
  except:
    - gh-pages

notifications:
  email:
    on_success: change
    on_failure: always