# References:
# https://github.com/mpeterv/hererocks
# https://github.com/kikito/middleclass/blob/master/.travis.yml
# http://luacheck.readthedocs.org/en/stable/cli.html#command-line-options

language: python
sudo: false

env:
  - LUA="lua=5.3"
  - LUA="luajit=2.1"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin # Add directory with all installed binaries to PATH

install:
  - luarocks install luacheck
  - luarocks install busted
  - luarocks install luacov

script:
  - ./scripts/lint.sh

notifications:
  email:
    on_success: change
    on_failure: always