return {
    SOUND_UTIL = 'src.util.sound_util',
    FILE_UTIL = 'src.util.file_util',
    CONSTANT_UTIL = 'src.util.constant_util',
    DISPLAY_CONSTANTS = 'src.constant.display',
    COLLISION_UTIL = 'src.util.collision_util',
    EVENT_UTIL = 'src.util.event_util',
    SWIPE_UTIL = 'src.util.swipe_util',
    DATABASE = 'src.db.db',
    DATABASE_CONSTANTS = 'src.constant.database_scripts',
    SCENE_MANAGER = 'src.scenes.manager',
    DEFAULTS = 'src.default.defaults',
    SETTINGS = 'src.db.settings',
    IMAGES = 'src.constant.images',
    LISTENER = 'src.constant.listener',
    SOUNDS = 'src.constant.sounds',
    SPRITE_SEQUENCE = 'src.constant.sprite_sequence',
    STRINGS = 'src.constant.strings',
    SQLITE3 = 'sqlite3',
    PHYSICS = 'physics',
    LFS = 'lfs',
    COMPOSER = 'composer',
    CRAZY_SCIENTIST_SPRITE = 'src.sprite.crazy_scientist',
    GAME_RULES = 'src.scenes.rules.game',
    PING_PONG = 'src.effect.ping_pong',
    SNOW = 'src.effect.snow',
    WIDGET = 'widget'
}