return {
    CRAZY_SCIENTIST = 'CRAZY_SCIENTIST',
    POWER_UP = 'POWER_UP',
    OBSTACLE = 'OBSTACLE',
    SHOT = 'SHOT',
    BOTTOM_WALL = 'BOTTOM_WALL',
    BEAR_ANIMAL = 'BEAR',
    TIGER_ANIMAL = 'TIGER'
}